# Generated by Django 4.2.9 on 2026-03-11 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, help_text='Custom display name for this contact', max_length=100)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_contacts',
                'ordering': ['contact__username'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(help_text='Device identifier', max_length=255)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('windows', 'Windows'), ('web', 'Web Browser')], max_length=50)),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('logged_in_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_token', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'user_devices',
                'ordering': ['-last_active_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_message_expiration_hours', models.IntegerField(default=24, help_text='Default message expiration time in hours')),
                ('theme_mode', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('auto', 'Auto')], default='light', max_length=20)),
                ('show_online_status', models.BooleanField(default=True)),
                ('show_last_seen', models.BooleanField(default=True)),
                ('show_read_receipts', models.BooleanField(default=True)),
                ('show_typing_indicators', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('notification_sound', models.BooleanField(default=True)),
                ('notification_vibrate', models.BooleanField(default=True)),
                ('app_lock_enabled', models.BooleanField(default=False)),
                ('app_lock_timeout_minutes', models.IntegerField(default=5)),
                ('screenshot_protection', models.BooleanField(default=True)),
                ('calendar_events_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='account_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='account_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='About info', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_groups',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_make_video_calls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_make_voice_calls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_send_files',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_send_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fingerprint_for_calls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='max_devices',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='online_status',
            field=models.CharField(choices=[('available', 'Available'), ('dnd', 'Do Not Disturb'), ('invisible', 'Invisible'), ('offline', 'Offline')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_android',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_ios',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_windows',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='require_fingerprint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('user_admin', 'User Admin'), ('system_admin', 'System Admin')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_token',
            field=models.CharField(blank=True, help_text='Encrypted Private Key', max_length=500),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_online'], name='users_is_onli_f24b46_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['online_status'], name='users_online__90b2b2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visible_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercontact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='visible_to', through='users.UserContact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'is_active'], name='user_device_user_id_14e9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['device_id'], name='user_device_device__945e98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercontact',
            unique_together={('user', 'contact')},
        ),
    ]
