# Generated by Django 4.2.9 on 2026-03-11 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('ended', 'Ended'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('room_id', models.CharField(max_length=255, unique=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('ringing_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('encrypted', models.BooleanField(default=True)),
                ('server_relay_enabled', models.BooleanField(default=False, help_text='Server relay for monitoring/lawful interception')),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_calls', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calls',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConferenceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('room_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended')], default='active', max_length=20)),
                ('max_participants', models.IntegerField(default=150)),
                ('password_protected', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('call_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='video', max_length=10)),
                ('allow_screen_sharing', models.BooleanField(default=True)),
                ('allow_recording', models.BooleanField(default=False)),
                ('voice_activated', models.BooleanField(default=True)),
                ('encrypted', models.BooleanField(default=True)),
                ('server_relay_enabled', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_conferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conference_calls',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CallSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(max_length=50)),
                ('signal_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='calls.call')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_signals_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'call_signals',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConferenceParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('host', 'Host'), ('moderator', 'Moderator'), ('participant', 'Participant')], default='participant', max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('joined', 'Joined'), ('left', 'Left'), ('removed', 'Removed')], default='invited', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_speaking', models.BooleanField(default=False)),
                ('audio_muted', models.BooleanField(default=False)),
                ('video_disabled', models.BooleanField(default=False)),
                ('is_screen_sharing', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_spotlighted', models.BooleanField(default=False)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='calls.conferencecall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conference_participants',
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['conference', 'is_active'], name='conference__confere_9e79e8_idx'), models.Index(fields=['user', 'status'], name='conference__user_id_75c90e_idx')],
                'unique_together': {('conference', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='conferencecall',
            index=models.Index(fields=['host', 'status'], name='conference__host_id_d4b537_idx'),
        ),
        migrations.AddIndex(
            model_name='conferencecall',
            index=models.Index(fields=['room_id'], name='conference__room_id_f1d9c6_idx'),
        ),
        migrations.AddIndex(
            model_name='conferencecall',
            index=models.Index(fields=['status'], name='conference__status_a0ef9a_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['caller', 'status'], name='calls_caller__8bffd9_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['receiver', 'status'], name='calls_receive_301de1_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['room_id'], name='calls_room_id_a82e0d_idx'),
        ),
    ]
