# Generated by Django 4.2.9 on 2026-03-11 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='secure_files/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('pdf', 'PDF'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=20)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='File expiration time (90 days default)', null=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('encrypted', models.BooleanField(default=True)),
                ('encryption_key', models.CharField(blank=True, max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='messaging.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='messaging.message')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('can_view', models.BooleanField(default=True)),
                ('can_download', models.BooleanField(default=True)),
                ('can_export', models.BooleanField(default=True)),
                ('can_share', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'file_permissions',
            },
        ),
        migrations.CreateModel(
            name='UserStorageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quota', models.IntegerField(default=500, help_text='Total storage quota in MB')),
                ('used_storage', models.BigIntegerField(default=0, help_text='Used storage in bytes')),
                ('max_file_size', models.IntegerField(default=20, help_text='Maximum file size in MB')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_storage_quotas',
            },
        ),
        migrations.CreateModel(
            name='FileRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_download', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('can_share', models.BooleanField(default=False)),
                ('accessed_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='files.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_recipients',
                'ordering': ['created_at'],
                'unique_together': {('file', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FileAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Viewed'), ('download', 'Downloaded'), ('share', 'Shared'), ('export', 'Exported'), ('delete', 'Deleted')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='files.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_access_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['file', '-timestamp'], name='file_access_file_id_489e85_idx'), models.Index(fields=['user', '-timestamp'], name='file_access_user_id_8b36f0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner', '-uploaded_at'], name='files_owner_i_56c1c1_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['conversation'], name='files_convers_1bdcff_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['expires_at'], name='files_expires_5cbb80_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['is_expired'], name='files_is_expi_074985_idx'),
        ),
    ]
